// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// persistence_from_cover
Rcpp::NumericMatrix persistence_from_cover(Rcpp::S4 cover);
RcppExport SEXP dca_persistence_from_cover(SEXP coverSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type cover(coverSEXP);
    rcpp_result_gen = Rcpp::wrap(persistence_from_cover(cover));
    return rcpp_result_gen;
END_RCPP
}
