# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Persistence from filtration
#' 
#' Calculate the persistence from the filtration
#' 
#' @param filtration A filtration
persistence_from_filtration <- function(filtration) {
    .Call('dca_persistence_from_filtration', PACKAGE = 'dca', filtration)
}

