# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Persistence from cover
#' 
#' Calculate the persistence from the cover
#' 
#' @param cover A cover
persistence_from_cover <- function(cover) {
    .Call('dca_persistence_from_cover', PACKAGE = 'dca', cover)
}

